global:
  scrape_interval: 30s
#  query_log_file: /etc/prometheus/query.log

rule_files:
  - /etc/prometheus/rules/*.yaml

scrape_configs:

  # This Prometheus scrape configuration pobes several http/https
  # targets from ping7.io's eu-central and us-east locations.
  - job_name: blackbox
    file_sd_configs:
      - files:
          - /etc/prometheus/blackbox/targets.yml
    metrics_path: /blackbox/probex^
    scheme: https
    scrape_interval: 5m
    authorization:
      # Your ping7.io API token stored in this file
      credentials_file: /etc/prometheus/ping7io-token
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [ module ]
        target_label: __param_module
      - source_labels: [ location ]
        target_label: __param_location
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        replacement: check.ping7.io


  #  - job_name: blackbox
#    metrics_path: /blackbox/probe
#    scheme: https
#    scrape_interval: 5m
#    authorization:
#      # Your ping7.io API token stored in this file
#      credentials_file: /etc/prometheus/ping7io-token
#    params:
#      module: [http_2xx] # Look for a HTTP 200 response.
#      location:
#        - eu-central # Probe from the eu-central location
#        - eu-north
#        - us-east    # Probe from the us-east location
#    static_configs:
#      - targets:
#          - http://prometheus.io # First probe
#          - https://ping7.io # Second probe
#          - https://google.com
#          - https://adsoul.com
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - source_labels: [__address__]
#        target_label: __address__
#        replacement: check.ping7.io
#      - source_labels: [ __param_location ]
#        target_label: location

  - job_name: ssl
    metrics_path: /tls/probe
    scheme: https
    scrape_interval: 15m
    scrape_timeout: 1m
    authorization:
      # Your ping7.io API token stored in this file
      credentials_file: /etc/prometheus/ping7io-token
    params:
      module: ["https"]
      location:
        - eu-central # Probe from the eu-central location
    static_configs:
      - targets:
          - ping7.io:443
          - prometheus.io:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        replacement: check.ping7.io
#      - source_labels: [__param_location]
#        target_label: location
