global:
  scrape_interval: 30s

rule_files:
  - /etc/prometheus/rules/*.yaml

scrape_configs:

  # This Prometheus scrape configuration pobes several http/https
  # targets from ping7.io's eu-central and us-east locations.
  - job_name: blackbox
    metrics_path: /blackbox/probe
    scheme: https
    authorization:
      # Your ping7.io API token stored in this file
      credentials_file: /etc/prometheus/ping7io-token
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
      location:
        - eu-central # Probe from these locations
        - eu-north
        - us-east
    static_configs:
      - targets:
          - http://prometheus.io # First probe
          - https://ping7.io # Second probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        replacement: check.ping7.io

  - job_name: ssl
    metrics_path: /tls/probe
    scheme: https
    scrape_interval: 15m # scrape only every 15 minutes as information is not
                         # going to change very often
    authorization:
      credentials_file: /etc/prometheus/ping7io-token
    params:
      module: ["https"]
      location:
        - eu-central
    static_configs:
      - targets:
          - prometheus.io:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        replacement: check.ping7.io

  - job_name: ssl-labs
    metrics_path: /ssllabs/probe
    scheme: https
    authorization:
      credentials_file: /etc/prometheus/ping7io-token
    params:
      module: ["https"]
    static_configs:
      - targets:
          - ping7.io
          - prometheus.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        replacement: check.ping7.io
