apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkping7io
  annotations:
    ping7.io/module: http_4xx
    ping7.io/scheme: https
spec:
  rules:
  - host: "check.ping7.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              number: 80
