apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: googlecom
  annotations:
    ping7.io/scrape: "false"
spec:
  rules:
  - host: "google.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              number: 80
