apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping7io
  annotations:
    ping7.io/path: "/imprint"
    ping7.io/scheme: "https"
    ping7.io/scrape: "true"
spec:
  rules:
  - host: "ping7.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              number: 80
