apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheusio
spec:
  rules:
  - host: "prometheus.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port:
              number: 80
