version: '2.4'
services:
  prometheus:
    image: prom/prometheus:v2.33.3
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    ports:
      - 9090:9090
    volumes:
      - ./rootfs/etc/prometheus:/etc/prometheus
#      - ./ping7io-token:/etc/prometheus/ping7io-token

#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    volumes:
#      - ./rootfs/etc/grafana:/etc/grafana
