{
 "title": "availability // ping7.io",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(probe_success, location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current status",
   "type": "grafana-polystat-panel",
   "description": "Current status by location consens",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (probe_success{instance=~\"$instance\"}) / scalar(count(count by (location) (probe_success)))",
     "legendFormat": "{{instance}} - {{location}}"
    }
   ]
  },
  {
   "title": "Percent uptime",
   "type": "stat",
   "description": "Percent uptime by location consens",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((sum by (instance) (probe_success{instance=~\"$instance\"}) / scalar(count(count by (location) (probe_success))) > 0.5)[1d:])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status history ",
   "type": "timeseries",
   "description": "Status history by location consens",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) (probe_success{instance=~\"$instance\"}) / scalar(count(count by (location) (probe_success)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Location details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Current status",
   "type": "grafana-polystat-panel",
   "description": "Current status for each location",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\", location=~\"$location\"}",
     "legendFormat": "{{instance}} - {{location}}"
    }
   ]
  },
  {
   "title": "Status history",
   "type": "timeseries",
   "description": "Status history for each location",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\", location=~\"$location\"}",
     "legendFormat": "{{instance}} - {{location}}"
    }
   ]
  },
  {
   "title": "HTTP response duration",
   "type": "timeseries",
   "description": "HTTP response duration for each location",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=~\"$instance\", location=~\"$location\"}) by (instance, location)",
     "legendFormat": "{{instance}} {{location}}"
    }
   ]
  },
  { "title": "SSL/TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "SSL/TLS Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\", location=~\"$location\"}"
    },
    {
     "expr": "probe_http_ssl{instance=~\"$instance\", location=~\"$location\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{instance=~\"$instance\", location=~\"$location\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{instance=~\"$instance\", location=~\"$location\"}"
    }
   ]
  },
  {
   "title": "SSL cert expiry in days (for alerts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (instance) (probe_ssl_earliest_cert_expiry{instance=~\"$instance\", location=~\"$location\"} - time()) / 3600 / 24",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}