version: '2.4'
services:
  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./rootfs/etc/prometheus:/etc/prometheus
      - ./ping7io-token:/etc/prometheus/ping7io-token
